### PR TITLE
Added RD_DS support

### PR DESCRIPTION
**Pull request by vdukhovni**
This adds support for decoding, encoding and displaying DS RRs.

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
I'm not sure that the CI failure is relating to your code. Any thoughts?

**Comment by vdukhovni** [comment]
It sure looks unrelated.
```
cabal: Error: some packages failed to install:
safe-0.3.14 failed during the configure step. The exception was:
user error (The package 'safe' requires Cabal library version -any && >=1.18
but no suitable version is installed.)
```
I guess we're now using a newer default version of `safe` that needs a newer GHC than 7.6.3?  Perhaps that configuration needs a lower maximum version of `safe`?  I'd expect the master branch to fail with 7.6.3 without my PR...

**Comment by vdukhovni** [comment]
Looks like `safe-0.3.12` changed to depend on `base (>=4.5 && <5)` while `0.3.11` had just `base (<5)`.
The changelog says:
```
 0.3.14
   #20, fix for GHC 7.10.1
0.3.13
   #20, require GHC 7.4 or above
0.3.12
  #19, add Safe.Partial exposing a Partial typeclass
  #19, add support for GHC call stacks
```
However, it seems that 7.4 may not be enough, or there's some other constraint that failed to be recorded.

**Comment by vdukhovni** [comment]
Could you look into it further?
https://github.com/ndmitchell/safe/issues/20

**Comment by kazu-yamamoto** [comment]
We don't have to keep GHC 7.6.
Also, this PR looks good to me.
So, merged. Thanks.
I would release a new version if you wish.

**Comment by vdukhovni** [comment]
Thanks.  No rush on a new release, I can keep using a private build for a while, perhaps there'll be other minor changes before you need to cut a new release.  Likely not too many folks other than me are getting their hands dirty with DNSSEC in Haskell.  There are more RRtypes we could add decoders for, I've not yet been inspired to start adding `RD_sometype` definitions for RRtypes I don't personally use.

**Comment by kazu-yamamoto** [comment]
Please ping me when you would like to have a new release.

**Pull request merged**
