### PR TITLE
Switch to github actions CI

### PR DESCRIPTION
**Pull request by vdukhovni**
Retrying github CI via guided setup... For now trying to avoid updating the main branch, but that may prove necessary.

### CODE REVIEW

**Comment by vdukhovni** [comment]
This is looking promising. Needs review.  The pre-installed cabal in Github CI [seems to be](https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners) 3.4.0.0 on Ubuntu and 3.2.0.0 on Windows and MacOS, the builds could perhaps go faster if we use those versions...

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Comment by vdukhovni** [comment]
> LGTM

Thanks, are there any improvements you'd want to make, or tweaks to the matrix?  Perhaps not test quite so many MacOS versions?  Thought I guess the tweaks can happen progressively in subsequent PRs as we gain experience with the new CI?

If you feel this is good to go, feel free to merge...

**Comment by kazu-yamamoto** [comment]
Merged.

**Comment by vdukhovni** [comment]
Do you know why appveyor still appears to be running?  Is it not enough to remove appveyor.yml?

**Pull request merged**
