### PR TITLE
Edns0

### PR DESCRIPTION
**Pull request by greydot**

### CODE REVIEW

**Comment by greydot** [comment]
Builds with GHC 7.0 and 7.4 fail because those versions lack the support for MultiWayIf syntax. Should I rewrite the code in question?

**Comment by kazu-yamamoto** [comment]
Yes. Please avoid using MultiWayIf at this moment.

**Comment by kazu-yamamoto** [comment]
I would like to check our code with three versions of GHC on travis CI. Unfortunately, travis does not support GHC 7.10 yet. So, I would keep GHC 7.4, 7.6 and 7.8 at this moment.

**Comment by greydot** [comment]
Done.

**Comment by greydot** [comment]
Looks like 7.0 and 7.4 builds still fail, and this time it's not my fault.

**Comment by kazu-yamamoto** [comment]
I will take care of it!

**Comment by greydot** [comment]
Thanks. Could you release a new version on hackage any time soon?

**Comment by kazu-yamamoto** [comment]
Tests on travis have been resolved.

**Comment by kazu-yamamoto** [comment]
I added some symbols for backward compatibility: 05269f769cd68b1078d592952c08a2b1ac99c0de

This is necessary for concurrent-dns-cache.

@greydot what do you think?

**Comment by greydot** [comment]
It's fine by me.

P.S. You might wanna add 7.10 build to iproute given that travis supports it now. Just a friendly reminder.

**Comment by kazu-yamamoto** [comment]
Oh, thanks. > iproute

**Comment by kazu-yamamoto** [comment]
I think we can release a new version tonight.
Would you write ChangeLog (as a new file) since the change is huge?

**Comment by greydot** [comment]
Ok. I'll send you a new pull request later today.

**Pull request merged**
